const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {spawn}=require('node:child_process');const {chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'..'),config=fs.mkdtempSync(path.join(os.tmpdir(),'pulse-perf-ui-'));const backend=spawn('python3',['pulse_backend.py'],{cwd:root,env:{...process.env,PULSE_CONFIG_DIR:config,PULSE_LITE_CONFIG_DIR:config,PULSE_PORT:'0'}});let browser;
try{const url=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('startup timeout')),15000);backend.stdout.on('data',chunk=>{const m=String(chunk).match(/http:\/\/127.0.0.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});backend.on('exit',code=>reject(Error('backend exited '+code)));});browser=await chromium.launch({headless:true,...(process.env.PULSE_BROWSER_CHANNEL?{channel:process.env.PULSE_BROWSER_CHANNEL}:{})});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>state.autosaveReady);
await page.evaluate(async()=>{const start=await fetch(backendUrl('/api/discovery/start'),{method:'POST',headers:apiHeaders({'Content-Type':'application/json'}),body:JSON.stringify({seedPapers:[{title:'Endpoint fixture'}],branches:{citationGraph:false,citationNetwork:false,semanticSearch:false,lexicalSearch:false}})});if(start.status!==202)throw Error('Job API failed to start');let job=await start.json();while(job.status==='running'){await new Promise(r=>setTimeout(r,20));job=await(await fetch(backendUrl('/api/discovery/jobs/'+job.id),{headers:apiHeaders()})).json();}if(job.status!=='complete'||job.recommendations.length)throw Error('Job API did not complete');});
const lite=await page.evaluate(()=>typeof MAX_PAPERS!=='undefined');
await page.evaluate(()=>{state.autosaveReady=false;state.papers=[{id:'seed',title:'Seed fixture',year:'2020',authors:[],text:'graph learning seed'}];state.selectedId='seed';state.pinnedSeedId='seed';render();});
let polls=0,cancelled=false;
await page.route('**/api/discovery/start',r=>r.fulfill({json:{id:'fixture',status:'running',total:4,recommendations:[]}}));
await page.route('**/api/discovery/jobs/fixture',r=>{polls++;return r.fulfill({json:{id:'fixture',status:'running',total:4,completed:1,recommendations:[{title:'Partial candidate',branch:'semanticSearch',score:70}]}});});
await page.route('**/api/discovery/cancel',r=>{cancelled=true;return r.fulfill({json:{status:'cancelled'}});});
await page.locator('#discoveryRunButton').click();await page.waitForFunction(()=>state.discoveryResults.length===1);assert.ok(polls>0);assert.match(await page.locator('#discoveryProgress').textContent(),/1 of 4/);await page.locator('#discoverySelectAllBtn').click();assert.equal(await page.locator('#discoveryAddSelectedMapBtn').isDisabled(),true,'Partial candidates cannot be added while search is changing');const cancelResponse=page.waitForResponse(r=>r.url().includes('/api/discovery/cancel'));await page.locator('#discoveryCancelButton').click();await cancelResponse;await page.waitForFunction(()=>!state.discoveryLoading);assert.ok(cancelled);assert.equal(await page.locator('#discoveryAddSelectedMapBtn').isDisabled(),false);assert.match(await page.locator('#discoveryProgress').textContent(),/cancelled/);
await page.unroute('**/api/discovery/start');await page.route('**/api/discovery/start',r=>r.fulfill({json:{status:'complete',completed:4,total:4,recommendations:[{title:'Final candidate',branch:'citationGraph',score:90}],errors:{semanticSearch:'Provider unavailable'}}}));await page.locator('#discoveryRunButton').click();await page.waitForFunction(()=>!state.discoveryLoading);assert.equal(await page.locator('.discovery-paper-item').count(),1);assert.match(await page.locator('#discoveryProgress').textContent(),/Provider unavailable/);
await page.locator('[data-rail="network"]').click();const n=lite?12:500;
const check=await page.evaluate(async n=>{state.papers=Array.from({length:n},(_,i)=>({id:'n'+i,title:'topic'+i+' graph notes',authors:[],text:'topic'+i+' scientific study findings methods',x:0,y:0}));state.explicitLinks=[{source:'n0',target:'n1',type:'citation',score:.98}];state.selectedId=null;state.inspectorOpen=false;let frames=0,heartbeats=0,alive=true;const heartbeat=setInterval(()=>heartbeats++,5);const tick=()=>{frames++;if(alive)requestAnimationFrame(tick);};requestAnimationFrame(tick);render();await waitForGraphIdle();alive=false;clearInterval(heartbeat);const stats={...graphStats};const node=document.querySelector('#map .node');state.selectedId='n1';render();return {frames,heartbeats,workerFailures:graphStats.workerFailures,sameNode:node===document.querySelector('#map .node'),analyses:graphStats.analyses-stats.analyses,layouts:graphStats.layouts-stats.layouts};},n);
assert.equal(check.sameNode,true,'Selection refresh preserves graph elements');assert.equal(check.analyses,0);assert.equal(check.layouts,0);if(!lite){assert.equal(check.workerFailures,0,'Worker analysis and layout succeed');assert.ok(check.heartbeats>0,'UI event loop remains responsive during worker analysis');}
await page.evaluate(()=>{const edge=document.querySelector('#map .edge');const id=edge.dataset.link;selectLinkage(id);if(!edge.classList.contains('is-selected'))throw Error('Retained edge did not highlight');clearLinkageSelection();if(edge.classList.contains('is-selected'))throw Error('Retained edge stayed highlighted');state.inspectorOpen=false;});
// An old worker result must not restore removed papers after a newer small library is loaded.
await page.evaluate(async()=>{if(typeof MAX_PAPERS==='undefined'){state.papers.push({id:'late',title:'late worker',authors:[],text:'late worker'});render();state.papers=state.papers.slice(0,200);render();state.papers=[{id:'kept',title:'kept',authors:[],text:'kept'}];state.explicitLinks=[];render();await waitForGraphIdle();}else{state.papers=[{id:'kept',title:'kept',authors:[],text:'kept'}];render();}});assert.equal(await page.evaluate(()=>state.papers.length),1);assert.equal(await page.locator('#map .node').count(),1);assert.equal(await page.evaluate(()=>state.links.length),0);
const pending=[],bodies=[];await page.route('**/api/library',r=>{if(r.request().method()==='POST'){bodies.push(r.request().postDataJSON());pending.push(r);}else return r.continue();});await page.evaluate(()=>{state.autosaveReady=true;saveLibrary();state.papers[0].title='intermediate';saveLibrary();state.papers[0].title='latest';saveLibrary();});await page.waitForTimeout(100);assert.equal(pending.length,1,'Only one save in flight');await pending[0].fulfill({json:{ok:true}});await page.waitForFunction(()=>true);await page.waitForTimeout(100);assert.equal(pending.length,2);assert.equal(bodies[1].papers[0].title,'latest','Queued saves coalesce to the latest snapshot');assert.ok(bodies[1]._saveRevision>bodies[0]._saveRevision);await pending[1].fulfill({json:{ok:true}});await page.evaluate(()=>saveLoop);const savedCount=bodies.length;await page.evaluate(()=>saveLibrary());assert.equal(bodies.length,savedCount,'Unchanged state avoids redundant saves');
await page.unroute('**/api/library');await page.route('**/api/library',r=>r.fulfill({status:503,json:{error:'offline'}}));await page.evaluate(()=>{state.papers[0].title='fallback';return saveLibrary();});assert.match(await page.locator('#save-state-pill').textContent(),/Saved locally/);
await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.includes('autosave-library'))throw new DOMException('full','QuotaExceededError');return original.call(this,key,value);};state.papers[0].title='not persisted';return saveLibrary();});assert.match(await page.locator('#save-state-pill').textContent(),/Save failed/);assert.deepEqual(errors,[]);console.log('PASS: discovery progress/cancel, partial results, provider errors, worker responsiveness, retained DOM, stale jobs, ordered saves, save failure reporting');
}finally{if(browser)await browser.close();backend.kill();fs.rmSync(config,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
