const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');const {chromium}=require('playwright');
(async()=>{
 const root=path.resolve(__dirname,'..'),config=fs.mkdtempSync(path.join(os.tmpdir(),'pulse-parity-'));
 const backend=spawn('python3',['pulse_backend.py'],{cwd:root,env:{...process.env,PULSE_CONFIG_DIR:config,PULSE_PORT:'0',PULSE_DISABLE_BUNDLED_OLLAMA:'1'}});let browser;
 try {
  const url=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Backend timeout')),15000);backend.stdout.on('data',c=>{const m=String(c).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});backend.on('exit',c=>reject(Error('Backend exited '+c)));});
  browser=await chromium.launch({headless:true,...(process.env.PULSE_BROWSER_CHANNEL?{channel:process.env.PULSE_BROWSER_CHANNEL}:{})});const page=await browser.newPage({viewport:{width:1400,height:920}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);await page.waitForFunction(()=>state.autosaveReady);
  assert.equal(await page.locator('[data-rail="collections"]').count(),0);
  for(const s of ['.pulse-col-library','.pulse-col-inspector'])assert.equal(await page.locator(s).isVisible(),true);
  await page.locator('[data-rail="timeline"]').click();assert.equal(await page.locator('#timelineView').isVisible(),true);assert.match(await page.locator('#timelineView').innerText(),/Add or import/);await page.locator('[data-rail="network"]').click();
  await page.locator('#quickSearchInput').fill('Graph methods for document retrieval');await page.locator('#quickAddBtn').click();await page.waitForFunction(()=>state.papers.length===1);
  await page.locator('#quickSearchInput').fill('Graph methods for document retrieval');await page.locator('#quickSearchInput').press('Enter');assert.equal(await page.evaluate(()=>state.papers.length),1);
  await page.locator('#quickSearchInput').fill('Document retrieval using graph learning');await page.locator('#quickAddBtn').click();await page.waitForFunction(()=>state.papers.length===2);
  await page.evaluate(()=>{state.papers[0].year='2024';state.papers[1].year='2018';state.papers.push({...state.papers[0],id:'unknown',title:'Paper without a publication year',year:'',date:''});render();});
  await page.locator('[data-rail="timeline"]').click();assert.deepEqual(await page.locator('.timeline-paper').evaluateAll(n=>n.map(p=>p.dataset.year)),['2018','2024','unknown']);await page.locator('#timelineOrder').selectOption('desc');assert.deepEqual(await page.locator('.timeline-paper').evaluateAll(n=>n.map(p=>p.dataset.year)),['2024','2018','unknown']);
  await page.locator('[data-timeline-paper]').first().click();assert.equal(await page.evaluate(()=>state.selectedId),await page.locator('[data-timeline-paper]').first().getAttribute('data-timeline-paper'));await page.locator('[data-timeline-graph]').first().click();assert.equal(await page.locator('#map').isVisible(),true);
  await page.locator('#canvasLinksSelect').selectOption('citation');assert.equal(await page.locator('#map .edge').count(),0);await page.locator('#canvasLinksSelect').selectOption('all');assert.ok(await page.locator('#map .edge').count()>0);
  await page.locator('#canvasLayoutSelect').selectOption('radial');assert.equal(await page.evaluate(()=>state.mode),'radial');await page.locator('#canvasLayoutSelect').selectOption('network');await page.locator('[data-mode="table"]').click();assert.equal(await page.locator('#tableView').isVisible(),true);await page.locator('[data-mode="network"]').click();
  await page.locator('#labelModeInput').selectOption('none');assert.equal(await page.locator('#map .node-label').count(),0);await page.locator('#showLabelsToggle').check();assert.equal(await page.locator('#labelModeInput').inputValue(),'short');
  await page.locator('[data-rail="trends"]').click();assert.equal(await page.evaluate(()=>state.mode),'clusters');await page.locator('[data-rail="network"]').click();
  for(const [open,panel,close] of [['#graphButton','#graphPanel','#graphCloseButton'],['#linkageButton','#linkagePanel','#linkageCloseButton'],['#areaButton','#areaPanel','#areaCloseButton'],['#aiButton','#aiPanel','#aiCloseButton']]){await page.locator(open).click();assert.equal(await page.locator(panel).isVisible(),true);await page.locator(close).click();}
  await page.locator('#theme-dark').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.locator('#theme-light').click();
  await page.locator('[data-rail="settings"]').click();assert.equal(await page.locator('#settingsPanel').isVisible(),true);await page.locator('[data-settings-tab="extraction"]').click();await page.locator('#autoGemmaInput').uncheck();await page.locator('[data-settings-tab="backend"]').click();await page.locator('#saveSettingsButton').click();await page.waitForFunction(()=>!els.saveSettingsButton.disabled);assert.equal(JSON.parse(fs.readFileSync(path.join(config,'settings.json'),'utf8')).autoGemmaExtraction,false);await page.locator('#settingsCloseButton').click();
  const requests=[];await page.route('**/api/discovery/pipeline',r=>{requests.push(r.request().postDataJSON());return r.fulfill({json:{ok:true,recommendations:[{title:'Related graph paper',doi:'10.1234/related',authors:['Test Author'],year:'2025',abstract:'Graph retrieval research',citedByCount:4}]}});});await page.locator('[data-depth="3"]').click();await page.locator('[data-rail="discover"]').click();await page.waitForFunction(()=>state.discoveryResults.length===1);assert.equal(requests[0].depth,'3');
  if(await page.locator('#discoveryModal').isVisible())await page.locator('#discoveryModalCloseButton').click();
  const download=page.waitForEvent('download');await page.locator('#exportButton').click();const map=await download;assert.equal(map.suggestedFilename(),'paper-linkage-map.json');const payload=JSON.parse(fs.readFileSync(await map.path(),'utf8'));assert.equal(payload.papers.length,3);
  const csv=page.waitForEvent('download');await page.locator('#summaryExportButton').click();assert.equal((await csv).suggestedFilename(),'pulse-summary-table.csv');
  await page.locator('#importInput').setInputFiles({name:'fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...payload,papers:[...payload.papers,{...payload.papers[0],id:'imported',title:'Imported record',year:'2022'}]}))});await page.waitForFunction(()=>state.papers.some(p=>p.id==='imported'));
  await page.waitForFunction(()=>document.querySelector('#save-state-pill').textContent.includes('Saved'));await page.reload();await page.waitForFunction(()=>state.autosaveReady&&state.papers.some(p=>p.id==='imported'));await page.locator('[data-rail="timeline"]').click();assert.equal(await page.evaluate(()=>state.mode),'timeline');assert.equal(await page.locator('.rail-item.active').getAttribute('data-rail'),'timeline');assert.equal(await page.locator('.subbar-tab.is-active').getAttribute('data-mode'),'timeline');assert.equal(await page.locator('#graphLegend').isVisible(),false);await page.evaluate(async()=>{els.toast.style.display='none';await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});await page.screenshot({path:path.join(root,'docs/images/timeline.png'),fullPage:true,animations:'disabled'});
  await page.evaluate(()=>{state.autosaveReady=false;loadSample();state.mode='network';render();});await page.screenshot({path:path.join(root,'docs/images/network.png'),fullPage:true,animations:'disabled'});await page.locator('[data-rail="timeline"]').click();await page.screenshot({path:path.join(root,'docs/images/timeline.png'),fullPage:true,animations:'disabled'});await page.locator('[data-rail="network"]').click();
  const count=await page.locator('#map .node').count();await page.locator('[data-action="toggle-paper-active"]').first().uncheck();assert.equal(await page.locator('#map .node').count(),count-1);await page.locator('[data-action="toggle-paper-active"]').first().check();assert.equal(await page.locator('#map .node').count(),count);
  await page.route('**/api/metadata/pmid',r=>r.fulfill({json:{metadata:{title:'PubMed fixture',pmid:'12345',year:'2021',authors:['Fixture'],doi:'10.1234/pmid',s2PaperId:'test-s2'}}}));await page.locator('#quickSearchInput').fill('PMID: 12345');await page.locator('#quickAddBtn').click();await page.waitForFunction(()=>state.papers.some(p=>p.pmid==='12345'));const afterPmid=await page.evaluate(()=>state.papers.length);await page.locator('#quickSearchInput').fill('12345');await page.locator('#quickAddBtn').click();assert.equal(await page.evaluate(()=>state.papers.length),afterPmid);assert.equal(await page.evaluate(()=>serializeMap().papers.find(p=>p.pmid==='12345').s2PaperId),'test-s2');
  await page.evaluate(()=>{state.autosaveReady=true;});page.once('dialog',dialog=>dialog.accept());await page.locator('[data-rail="settings"]').click();await page.locator('[data-settings-tab="storage"]').click();await page.locator('#clearAppToDefaultButton').click();await page.waitForFunction(()=>state.papers.length===0&&els.settingsPanel.hidden);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(config,'library.json'),'utf8')).papers,[]);
  assert.deepEqual(errors,[]);console.log('PASS: 1.2 workspace controls, timeline, graph filters/layouts, settings, discovery depth, imports/exports and persistence');
 }finally{if(browser)await browser.close();backend.kill();fs.rmSync(config,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exit(1);});
