const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../pulse-frontend/js/part_24.js'),'utf8');
const main=source.slice(0,source.indexOf("document.getElementById('libraryBulkDeselect').addEventListener"));
const elements=new Map();const handlers={};
const input={checked:false,indeterminate:false,addEventListener(name,fn){handlers[name]=fn;}};
const document={getElementById(id){if(id==='librarySelectVisible')return input;if(!elements.has(id))elements.set(id,{textContent:'',disabled:false,hidden:false});return elements.get(id);}};
const state={papers:[{id:'a',title:'Paper A',paperKeywords:['old']},{id:'b',title:'Paper B',paperKeywords:[]},{id:'c',title:'Paper C',paperKeywords:[]}],librarySelectedIds:new Set(['a','c']),libraryFullscreen:true};
const downloads=[];
const context={state,document,els:{paperList:{querySelectorAll:()=>[]}},paperMatchesFilters:()=>true,renderPapers:()=>{},render:()=>{},splitKeywords:v=>v.split(';').map(t=>t.trim()).filter(Boolean),csvCell:v=>'"'+String(v||'')+'"',recordRis:papers=>papers.map(p=>p.title).join('\n'),downloadRecordFile:(...args)=>downloads.push(args),serializeMap:()=>({papers:state.papers,links:[{source:'a',target:'b'},{source:'a',target:'c'}],clusters:[['a','b','c']],selectedId:'b',centerId:'b'}),AbortSignal};
vm.createContext(context);vm.runInContext(main,context);
context.renderLibraryBulkActions([state.papers[0],state.papers[1]]);
assert.equal(input.indeterminate,true);assert.equal(elements.get('libraryBulkCount').textContent,'2 selected · 1 outside this filter');
input.checked=true;handlers.change();assert.deepEqual([...state.librarySelectedIds],['a','c','b']);
input.checked=false;handlers.change();assert.deepEqual([...state.librarySelectedIds],['c']);
state.librarySelectedIds=new Set(['a','c']);context.tagLibrarySelection('new; old');
assert.equal(state.papers[0].paperKeywords.join(';'),'old;new');assert.equal(state.papers[1].paperKeywords.length,0);assert.equal(state.papers[2].paperKeywords.join(';'),'new;old');
for(const format of ['ris','csv','json'])context.exportLibrarySelection(format);
assert(!downloads[0][1].includes('Paper B'));assert(!downloads[1][1].includes('Paper B'));
const payload=JSON.parse(downloads[2][1]);assert.deepEqual(payload.papers.map(p=>p.id),['a','c']);assert.equal(payload.links.length,1);assert.equal(payload.selectedId,null);
const managerSource=fs.readFileSync(path.join(__dirname,'../pulse-frontend/js/part_23.js'),'utf8');
vm.runInContext(managerSource.slice(managerSource.indexOf('function managerSelectedPapers()'),managerSource.indexOf('function updateManagers()')),context);
elements.set('managerScope',{value:'bulk'});assert.equal(context.managerSelectedPapers().map(p=>p.id).join(','),'a,c');
console.log('PASS: visible-only select all, hidden selection count, selected-only tagging, exports, and transfer scope.');
